    // <!-- <p class="site-subtitle" itemprop="description">{{ subtitle }}</p> -->



document.addEventListener("DOMContentLoaded", function () {
    var paragraphs = [
        "AAA全国可飞加我看小男娘",
        "无糖可乐和有糖的, 相比之下,<br>冰镇可乐, 喝的更痛快.",
        "前有绝景, 敬请见证.",
        "再添加一个段落以供随机选择.",
        "<span style='color: red;'>这句话是红色的.</span>",
        "My eyes are open.",
        "Memento Mori.",
        "we will get out of babbdi",
        "谁也不会把迷宫的出口告诉小白鼠的, 伦吾同学.",
        "那些没有天赋的人呢?",
        "本人今年就30了, 和很多校友一样",
        "即使引导早已破碎,<br>也请您当上艾尔登之王.",
        "我考, 完啦",
        "任何人来打扰我干正事,<br>我都会停下来和他玩",
        "没有爱可以活下去, 但没有水不行.",
        "偶洅匜ハモえ菗潒ろ",
        "多勢に無勢 もう負け犬決定",
        "再见, 老七",
        "赌书消得泼茶香,<br>当时只道是寻常.",
        "欲买桂花同载酒,<br>终不似, 少年游.",
        "我未成名君未嫁,<br>可能俱是不如人.",
        "多少事, 从来急;<br>天地转, 光阴迫.<br>一万年太久, 只争朝夕.<br>四海翻腾云水怒, 五洲震荡风雷激.<br>要扫除一切害人虫, 全无敌.",
        "当烧到一百三十五万时, 水开了.",
        "啊啊啊啊啊<br>啊啊啊啊啊<br>啊啊啊啊啊<br>啊啊啊啊唉",
        "I was cured, all right.",
        "Keep on keeping on.",
        "Don't be so serious.",
        "Once there was an explosion",
        "知君命不偶, 同病亦同忧.",
        "等闲变却故人心,<br>却道故人心易变.",
        "欢迎使用华为备忘录. 您可以使用备忘录快速记录所思所想, 创建笔记, 清单以及待办事项.",
        "一光栅宽5cm, 每1mm有400条刻线, 波长500nm光波正入射时, 第二级衍射谱的衍射角最接近于",
        "如果你能认出Subtitle里的所有梗可以联系我, 我愿意v你50",
        "你的电影, 超~~级好看",
        "骗你的, 我们不去看电影",
        "95%的可能我们会寄",
        "我不想吃拼好饭了, 我想被爱",
        "It's not faith you need.<br>It's fear.",
        "喜剧就是重复, 喜剧就是重复, 喜剧就是重复, 喜剧就是重复, 喜剧就是重复, 喜剧就是重复, 喜剧就是重复.",
        "愿您坦然释怀",
        "永远别放弃!",
        "愿指引明路的苍蓝星为你闪耀",
        "&lt;script>alert(1)&lt;/script>",
        "你终于醒了, 现在是2019年, 我们一起玩MC",
        "诸位祖先, 敬请见证!",
        "我只是嘴甜, 我心里没你",
        "我在跟你说现在的事.",
        "嘻嘻, 我一定要活下去",
        "不要害怕,<br>最终我们每个人都会幸福快乐.",
        "不要在晚上做任何决定.<br>(这条是在凌晨两点写的)",
        "'or 1=1#",
        "早知道就活得再任性一点了.",
        "你好中国!",
        "事情就是这样.",
        "叽-啁-叽?",
        "啊呀呀半夜时钟刚刚敲过,<br>呜呼呼他娘的霉运老跟着我.",
        "算, 称, 分",
        "可惜你不写博客, 也不知道这句Subtitle的分量...",
        "有些人口中的看不见未来<br>其实是看见了未来",
        "你知道吗:<br>放坏的香蕉比正常的香蕉更通便.",
        "征服世界失败, 我被瑞士干掉了.",
        "太好了, 我逐渐理解一切",
        "Escape, now",
        "Subtitle加载失败,<br>请刷新页面重试.",
        // "幸福就像巧克力,<br>我这种狗一吃就似了.",
        "逮住蛤蟆, 攥出尿来.",
        "生活就像海洋,<br>只有意志坚强的人, 才能到达彼岸.",
        "<b>活下去</b>",
        "CAW! CAAAW!",
        "慢慢地慢慢地像被勒紧脖子一般地<br>把直到昨天的我逐渐杀死",
        "你尚未连接.<br>Web因你而不同.",
        "适当地 自由地<br>苟活下去",
        "@edmundmcmillen You litte F**ker<br>You made a shit of piece with your trash Issac it's f**King Bad this trash game I will become back my money I hope you will in your next time a cow on a trash farm you sucker",
        "Misery is wasted on the miserable.",
        "按部就班的发疯",
        "oiiaiooiiiai",
        "出售大脑, 全新未使用",
        "I miss the old days I couldn't tell.",
        "认清形势, 放弃幻想.",
        "我能在拥有失忆症的情况下通关地球OL吗",
        "I said I'm fine!",
        "永怀初心",
        "我真的变成坚韧了吗?",
        "爱的反义词不是恨, 是冷漠.",
        "哈!",
        "休息一天, 钓鱼去吧.<br>但愿仍然有鱼可钓.",
        "广告位招租",
        "我想了好久要把一句话加进来, 一直拖着没做, 现在忘了是哪句话",
        "死很容易, 喜剧最难.",
        "S'all good, man.",
        "坚持到底并不重要!",
        "让我们从阳台上看看星星吧",
        "从前种种, 譬如昨日死;<br>从后种种, 譬如今日生.",
        "Also try GitLab!",
        "真正严肃的哲学问题只有一个",
        "救救我! 我被困在这个网站的Subtitle里了!",
        "他说风雨中这点痛算什么<br>擦干泪不要怕至少我们还有梦",
        "你说你↗不想↘在这里",
        "花有重开日, 人无再少年.",
        "埋骨何须桑梓地,<br>人生无处不青山.",
        "五花马, 千金裘,<br>呼儿将出换美酒,<br>与尔同销万古愁.",
        "访问本站即表明您同意本站的用户服务政策, 每周四需向我转账50元.",
        "*意义不明的鼓点*",
        "人有所操",
        "The world is a cat<br>playing with Australia",
        "神说, 要有光,<br>就有了光.<br>他看光是好的,<br>就把光速设定为299,792,458m/s,<br>并让之永远不变,<br>不应参照系的改变而改变.",
        "BONFIRE LIT",
        "Tell them I said something smart.",
        "好吧, 你赢了.<br>你的音乐品味<br>小众又高级.",
        "能不能再放一遍?",
        "接受所有饼干",
        "浴室里没有人, 水是我开的.",
        "<span style='display:inline-block; transform: rotate(180deg);'>恰恰相反</span>",
        "循此苦旅, 直抵群星.",
        'Who/what is "Adam"?',
        "在他之上, 空无所有.",
        "Attention Is All You Need",
        "这台手术很成功,<br>我失败的人生结束了.",
        "天才就是99%的天才<br>加上1%的天才",
        "Nobody knows what's inside of me",
        "在坚冰还盖着北海的时候,<br>我看到了怒放的梅花.",
        "此地长眠者<br>声名水上书",
        "Faith, Alfred. Faith.",
        "是不是少了一抹奇幻色彩?",
        "得挠人处且挠人",
        "我不是那种你刺激我我就会努力的<br>你再刺激我我就跳楼了",
        "Is this the real life?<br>Is this just Fanta Sea?",
        "服务器繁忙, 请稍后再试.",
        "努力 未来<br>A BEAUTIFUL STAR",
        "我忘记了所有悲剧,<br>看到的都是奇迹…",
        "他肯定觉得这堆破句子老有意思了",
        "生活就像国际象棋<br>我不会下国际象棋",
        "Viva La Vida.",
        "既见君子, 云胡不喜?",
        "要想见证尘封的秘密,<br>就要承受最严厉的惩罚.",
        "Some things happen by chance.<br>And some things happen<br>because we make them happen.",
        "Please Do Not Throw<br>Sausage Pizza Away",
        "一曲忠诚的赞歌",
        "在那高远的黑色穹顶下,<br>它的牺牲使圣巢永世不衰.",
        "JMM",
        "事已至此, 先吃饭吧.",
        "Bye Bye Baby Blue",
        "不 挑 战<br>怕 战 胜<br>困 困 困<br>难 难 难",
        "据说每一群蝉要在地下闷17年,<br>鸣叫两个月然后死掉,<br>和刚刚高考完的那个暑假一模一样.",
        "不过, 他会想出来的.",
        "Aal izz well.",
        "茕茕白兔, 东走西顾.<br>衣不如新, 人不如故.",
        "我有一所房子,<br>面朝大海, 春暖花开.",
        "命使我乃鬼殺奸除",
        "I wanted to give you this<br>as a reminder...<br>not to look back.",
        "人到洛阳花似锦,<br>偏我来时不逢春.",
        "我们是不死之身.",
        "在一切都被改变的未来再会",
        "听: 隔壁是个绝对美好的宇宙;<br>我们走吧.",
        "我对你透露一个大秘密,<br>这是人类最古老的玩笑:<br>向哪走, 都是向前走.",
        "可能没有任何人比骑士卡托自己<br>更恨骑士卡托了.",
        "如果有一天我变得很有钱",
        "42",
        "满地都是六便士,<br>他却抬头看到了九磅十五便士.",
        "东风夜放花千树,<br>更吹落, 星如雨.",
        "三十年河南, 三十年河北",
        "Peace Among Worlds",
        "你真的想让我去死吗?",
        "大家死不是大家居住",
        "古来圣贤皆寂寞,<br>惟有饮者留其名.",
        "有时候我想...<br>然后我忘了",
        "宝宝, 你是一个**kwargs",
        "每个成功男人的背后,<br>都有一条脊椎.",
        "好好吃饭",
        "Bone ApplePie!",
        "Always like this.",
        "生年不满百, 常怀千岁忧.<br>昼短苦夜长, 何不秉烛游!",
        "这个月薯条亏损二十六箱,<br>你有头绪吗?",
        "请往前走<br>不要在此停留",
        "青青子衿, 悠悠我心.<br>但为君故, 沉吟至今.",
        "世界以痛吻我,<br>我报之以哈气.",
        "指鹿为马, 不负韶华.",
        "只要我还活着,<br>我就不会让人类灭绝这件事发生.",
        "耶&#12288;复活了",
        "我司雇我在",
        "这该死的沙漠!<br>我们都会淹死在这里.",
        "Get busy living, or get busy dying.",
        "梦想一斤七毛五",
        "这个人很懒, 什么也没留下.",
        "只是睡着了",
        "恐龙耗尽英雄气,<br>哺乳尽是鼠辈出.",
        "Time flies like an arrow<br>Fruit flies like a banana",
        "哇这个好可爱呀",
        "我的研究表明, 世界上存在一个直径800米左右的球体, 且味道还不错",
        "没有证据是没有的弱证据",
        "吾不识青天高, 黄地厚.<br>唯见月寒日暖, 来煎人寿.",
        "Get me off your fucking mailing list",
        "太阳照常升起",
        "宝宝due due delay了",
        "<span style='color: transparent;'>呀哈哈! 我被发现了!</span>",
        "生活就像一盒巧克力<br>我就像一条狗",
        "他们生也快乐, 死也快乐,<br>杯子里面总有酒喝.",
        "Adults are just obsolete children<br>and the hell with them.",
        "须知少日拏云志,<br>曾许人间第一流.",
        "事情变得有趣起来了啊",
        "时来天地皆同力,<br>运去英雄不自由.",
        "哇多麼好的機會啊",
        '<div class="formula">π<sup>4</sup> + π<sup>5</sup> ≈ e<sup>6</sup></div>',
        "安能摧眉折腰事权贵,<br>使我不得开心颜!",
        "山在70公里以外",
        "土豆爆炸!",
        "Powered by Electricity!",
        "基本无害",
        "比起精神出轨和肉体出轨<br>火车出轨更为伤人",
        "最是人间留不住,<br>朱颜辞镜花辞树.",
        "刚刚发生了什么?",
        "早起的鸟儿有普罗米修斯吃",
        "Checkmate is now unavoidable.",
        "你变得懦弱了, 老东西",
        "WAS HERE",
        "只有风暴才能击倒大树",
        "行不得也, 哥哥",
        "井, 井, 井",
        "子非我, 安知我非鱼?",
        "Let's go Justin!",
        "El Psy Kongroo",
        "你们两家都倒八辈子霉去吧!",
        "历史就是死人名字",
        "据不完全统计,<br>一年有11个月.",
        "418 I'm a teapot",
        "在这个年代, 找不到浪漫",
        "来到了天津卫, 嘛也没学会",
        "46. Qe4+ Rg6",
        "Only a fool would take anything posted here as fact.",
        "When I knew him, he was.",
        "Lorem ipsum dolor sit amet,<br>consectetur adipiscing elit.",
        "Don't you dare go Hollow.",
        "+C",
        "与心爱的你行至世界尽头",
        "胜败乃兵家常事,<br>大侠请重新来过.",
        "凡可以被真相摧毁的<br>都应该被真相摧毁",
        "Now on Firefox!",
        "🥔",
        "O brave new world,<br>That has such people in't.",
        "我恨你",
        "我爱你",
        "You are the player.<br>Wake up.",
        "Tomorrow is in your hands.",
        "Understand.",
        "上帝赐予我<br>接受我无法改变之事物的平静,<br>改变可改变之事物的勇气,<br>以及区分这两者之不同的<br>永恒智慧.",
        "十七张牌你能秒我?",
        "字母G其实是一个旋转的箭头",
        "But man is not made for defeat.",
        "宇宙很大, 生活更大,<br>我们一定还有缘相见.",
        "一个半小时是三个半小时"
    ];
    var randomIndex = Math.floor(Math.random() * paragraphs.length);
    var selectedParagraph = paragraphs[randomIndex];
    document.getElementById('randomParagraph').innerHTML = selectedParagraph;
});