// <!-- <p class="site-subtitle" itemprop="description">{{ subtitle }}</p> -->



document.addEventListener("DOMContentLoaded", function () {
    var paragraphs = [
        "AAA全国可飞加我看小男娘",
        "无糖可乐和有糖的, 相比之下,<br>冰镇可乐, 喝的更痛快.",
        "前有绝景, 敬请见证.",
        "再添加一个段落以供随机选择.",
        "<span style='color: red;'>这句话是红色的.</span>",
        "My eyes are open.",
        "Memento Mori.",
        "we will get out of babbdi",
        "谁也不会把迷宫的出口告诉小白鼠的, 伦吾同学.",
        "那些没有天赋的人呢?",
        "本人今年就30了, 和很多校友一样",
        "即使引导早已破碎,<br>也请您当上艾尔登之王.",
        "我考, 完啦",
        "任何人来打扰我干正事,<br>我都会停下来和他玩",
        "没有爱可以活下去, 但没有水不行.",
        "偶洅匜ハモえ菗潒ろ",
        "多勢に無勢 もう負け犬決定",
        "再见, 老七",
        "赌书消得泼茶香,<br>当时只道是寻常.",
        "欲买桂花同载酒,<br>终不似, 少年游.",
        "我未成名君未嫁,<br>可能俱是不如人.",
        "多少事, 从来急;<br>天地转, 光阴迫.<br>一万年太久, 只争朝夕.<br>四海翻腾云水怒, 五洲震荡风雷激.<br>要扫除一切害人虫, 全无敌.",
        "当烧到一百三十五万时, 水开了.",
        "啊啊啊啊啊<br>啊啊啊啊啊<br>啊啊啊啊啊<br>啊啊啊啊唉",
        "I was cured, all right.",
        "Keep on keeping on.",
        "Don't be so serious.",
        "Once there was an explosion",
        "知君命不偶, 同病亦同忧.",
        "等闲变却故人心,<br>却道故人心易变.",
        "欢迎使用华为备忘录. 您可以使用备忘录快速记录所思所想, 创建笔记, 清单以及待办事项.",
        "一光栅宽5cm, 每1mm有400条刻线, 波长500nm光波正入射时, 第二级衍射谱的衍射角最接近于",
        "如果你能认出Subtitle里的所有梗可以联系我, 我愿意v你50",
        "你的电影, 超~~级好看",
        "骗你的, 我们不去看电影",
        "95%的可能我们会寄",
        "我不想吃拼好饭了, 我想被爱",
        "It's not faith you need.<br>It's fear.",
        "关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!关注加州消防栓!!!",
        "愿您坦然释怀",
        "永远别放弃!",
        "愿指引明路的苍蓝星为你闪耀",
        "&lt;script>alert(1)&lt;/script>",
        "你终于醒了, 现在是2019年, 我们一起玩MC",
        "诸位祖先, 敬请见证!",
        "我只是嘴甜, 我心里没你",
        "我在跟你说现在的事.",
        "嘻嘻, 我一定要活下去",
        "不要害怕,<br>最终我们每个人都会幸福快乐.",
        "不要在晚上做任何决定.<br>(这条是在凌晨两点写的)",
        "'or 1=1#",
        "早知道就活得再任性一点了.",
        "你好中国!",
        "事情就是这样.",
        "叽-啁-叽?",
        "啊呀呀半夜时钟刚刚敲过,<br>呜呼呼他娘的霉运老跟着我.",
        "算, 称, 分",
        "可惜你不写博客, 也不知道这句Subtitle的分量...",
        "有些人口中的看不见未来其实是看见了未来.",
        "你知道吗:<br>放坏的香蕉比正常的香蕉更通便.",
        "征服世界失败, 我被瑞士干掉了.",
        "太好了, 我逐渐理解一切",
        "Escape, now",
        "Subtitle加载失败,<br>请刷新页面重试.",
        "幸福就像巧克力,<br>我这种狗一吃就似了.",
        "逮住蛤蟆, 攥出尿来.",
        "生活就像海洋,<br>只有意志坚强的人, 才能到达彼岸.",
        "<b>活下去</b>",
        "CAW! CAAAW!",
        "慢慢地慢慢地像被勒紧脖子一般地<br>把直到昨天的我逐渐杀死",
        "你尚未连接.<br>Web因你而不同.",
        "适当地 自由地<br>苟活下去",
        "@edmundmcmillen You litte F**ker<br>You made a shit of piece with your trash Issac it's f**King Bad this trash game I will become back my money I hope you will in your next time a cow on a trash farm you sucker",
        "Misery is wasted on the miserable.",
        "按部就班的发疯",
        "oiiaiooiiiai",
        "出售大脑, 全新未使用",
        "I miss the old days I couldn't tell.",
        "认清形势, 放弃幻想.",
        "我能在拥有失忆症的情况下通关地球OL吗",
        "I said I'm fine!",
        "永怀初心",
        "我真的变成坚韧了吗?",
        "爱的反义词不是恨, 是冷漠.",
        "哈!",
        "休息一天, 钓鱼去吧.<br>但愿仍然有鱼可钓.",
        "广告位招租",
        "我想了好久要把一句话加进来, 一直拖着没做, 现在忘了是哪句话",
        "死很容易, 喜剧最难.",
        "S'all good, man.",
        "坚持到底并不重要!",
        "让我们从阳台上看看星星吧",
        "从前种种, 譬如昨日死;<br>从后种种, 譬如今日生.",
        "Also try GitLab!",
        "真正严肃的哲学问题只有一个",
        "救救我! 我被困在这个网站的Subtitle里了!",
        "他说风雨中这点痛算什么<br>擦干泪不要怕至少我们还有梦",
        "你说你↗不想↘在这里",
        "花有重开日, 人无再少年.",
        "埋骨何须桑梓地,<br>人生无处不青山.",
        "五花马, 千金裘,<br>呼儿将出换美酒,<br>与尔同销万古愁.",
        "访问本站即表明您同意本站的用户服务政策, 每周四需向我转账50元.",
        "*意义不明的鼓点*",
        "人有所操",
        "The world is a cat<br>playing with Australia",
        "神说, 要有光,<br>就有了光.<br>他看光是好的,<br>就把光速设定为299,792,458m/s,<br>并让之永远不变,<br>不应参照系的改变而改变.",
        "BONFIRE LIT",
        "Tell them I said something smart.",
        "好吧, 你赢了.<br>你的音乐品味<br>小众又高级.",
        "能不能再放一遍?",
        "接受所有饼干",
        "浴室里没有人, 水是我开的.",
        "<span style='display:inline-block; transform: rotate(180deg);'>恰恰相反</span>",
        "循此苦旅, 直抵群星.",
        'Who/what is "Adam"?',
        "在他之上, 空无所有.",
        "Attention Is All You Need",
        "这台手术很成功,<br>我失败的人生结束了.",
        "天才就是99%的天才<br>加上1%的天才",
        "Nobody knows what's inside of me",
        "在坚冰还盖着北海的时候,<br>我看到了怒放的梅花.",
        "此地长眠者<br>声名水上书",
        "Faith, Alfred. Faith.",
        "是不是少了一抹奇幻色彩?",
        "得挠人处且挠人",
        "我不是那种你刺激我我就会努力的<br>你再刺激我我就跳楼了",
        "Is this the real life?<br>Is it just Fanta Sea?",
        "服务器繁忙, 请稍后再试.",
        "努力 未来<br>A BEAUTIFUL STAR",
        "我忘记了所有悲剧,<br>看到的都是奇迹…",
        "他肯定觉得这堆破句子老有意思了",
        "生活就像国际象棋<br>我不会下国际象棋",
        "Viva La Vida.",
        "既见君子, 云胡不喜?",
        "要想见证尘封的秘密,<br>就要承受最严厉的惩罚.",
        "Some things happen by chance.<br>And somethings happen<br>because we make them happen.",
        "Please Do Not Throw<br>Sausage Pizza Away",
        "一曲忠诚的赞歌",
        "在那高远的黑色穹顶下,<br>它的牺牲使圣巢永世不衰.",
        "JMM",
        "事已至此, 先吃饭吧.",
        "Bye Bye Baby Blue",
        "不挑战<br>怕战胜<br>困困困<br>难难难",
        "据说每一群蝉要在地下闷17年,<br>鸣叫两个月然后死掉,<br>和刚刚高考完的那个暑假一模一样."
    ];
    var randomIndex = Math.floor(Math.random() * paragraphs.length);
    var selectedParagraph = paragraphs[randomIndex];
    document.getElementById('randomParagraph').innerHTML = selectedParagraph;
});
